spring:
  config:
    import: classpath:application-secret.yml

  application:
    name: liskov-backend

  profiles:
    active: secret
  jpa:
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL9InnoDBDialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug

ai:
  url: http://zipchak.yjm.ai:8080

cors:
  allowed-origins:
    - "http://localhost:5173"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "*"
  allow-credentials: true