spring:
  config:
    import: classpath:application-secret.yml

  application:
    name: liskov-backend

  profiles:
    active: secret
  jpa:
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL9InnoDBDialect

logging:
  level:
    org.hibernate.SQL: debug

ai:
    url: http://ai.zipchak-backend.kro.kr
